apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: quality-authenticator
      component: postgres
  template:
    metadata:
      labels:
        app: quality-authenticator
        component: postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/redhat-appstudio-qe/postgres:14
          env:
          - name: PGDATA
            value: /work/data
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: dex-db
                key: storage-database
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dex-db
                key: storage-password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: dex-db
                key: storage-user
          ports:
          - containerPort: 5432
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
          - name: data
            mountPath: /work
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: quality-authenticator
    component: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
