---
apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: postgres # Set the name of the deployment
spec:
  replicas: 1 # Set 3 deployment replicas
  selector:
    matchLabels:
      app: quality-authenticator
      component: postgres
  template:
    metadata:
      labels:
        app: quality-authenticator
        component: postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/redhat-appstudio-qe/postgres:14
          env:
          - name: PGDATA
            value: /work/data
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: dex-db
                key: storage-database
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dex-db
                key: storage-password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: dex-db
                key: storage-user
          ports:
          - containerPort: 5432
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
          - name: data-postgres-1
            mountPath: /work
      volumes:
      - name: data-postgres-1
        emptyDir:
          sizeLimit: 500Mi