---
apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: postgres # Set the name of the deployment
spec:
  replicas: 1 # Set 3 deployment replicas
  selector:
    matchLabels:
      app: quality-authenticator
      component: postgres
  template:
    metadata:
      labels:
        app: quality-authenticator
        component: postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/redhat-appstudio-qe/postgres:14
          env:
          - name: PGDATA
            value: /work/data
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: dex-db
                key: storage-database
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dex-db
                key: storage-password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: dex-db
                key: storage-user
          ports:
          - containerPort: 5432
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
          - name: data
            mountPath: /work
      volumes:
        - name: postgres-volume-claim
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: PersistentVolume # Create PV
metadata:
  name: postgres-volume # Sets PV name
  labels:
    component: postgres
    app: quality-authenticator
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/work" # Sets PV's host path
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: postgres-volume-claim # Sets PVC's name
  labels:
    app: quality-authenticator # Defines app to create PVC for
    component: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # Sets PVC's size
